fixing syntax error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,7 +25,8 @@ jobs:
           if [ "$SUPER_SECRET" == "girliest secret" ]; then
             echo "Secret verified successfully!"
           else
-            echo "Secret verification failed!"; exit 1
+            echo "Secret verification failed!" && exit 1
+          fi
 
       - name: Lint code
         working-directory: ./jasmine-karma-documentation
